pap_mse_list = []
pap_ql_list = []
pap_lnSE_list = []
pap_PredVol_list = []

lr_optimal_n_list = []
lr_mse_list = []
lr_ql_list = []
lr_lnSE_list = []
lr_PredVol_list = []

rr1_mse_list = []
rr1_ql_list = []
rr1_lnSE_list = []
rr1_PredVol_list = []
rr1_optimal_log_lambda_list = []

rr2_mse_list = []
rr2_ql_list = []
rr2_lnSE_list = []
rr2_PredVol_list = []
rr2_optimal_n_list = []
rr2_optimal_log_lambda_list = []

brr_mse_list = []
brr_ql_list = []
brr_lnSE_list = []
brr_PredVol_list = []
brr_optimal_n_list = []
brr_optimal_log_alpha1_list = []
brr_optimal_log_alpha2_list = []
brr_optimal_log_lambda1_list = []
brr_optimal_log_lambda2_list = []

krr_linear_mse_list = []
krr_linear_ql_list = []
krr_linear_lnSE_list = []
krr_linear_PredVol_list = []
krr_linear_log_alpha_list = []
krr_linear_gamma_list = []

krr_Gaussian_mse_list = []
krr_Gaussian_ql_list = []
krr_Gaussian_lnSE_list = []
krr_Gaussian_PredVol_list = []
krr_Gaussian_log_alpha_list = []
krr_Gaussian_gamma_list = []

krr_rbf_mse_list = []
krr_rbf_ql_list = []
krr_rbf_lnSE_list = []
krr_rbf_PredVol_list = []
krr_rbf_log_alpha_list = []
krr_rbf_gamma_list = []

krr_chi2_mse_list = []
krr_chi2_ql_list = []
krr_chi2_lnSE_list = []
krr_chi2_PredVol_list = []
krr_chi2_log_alpha_list = []
krr_chi2_gamma_list = []

krr_sigmoid_mse_list = []
krr_sigmoid_ql_list = []
krr_sigmoid_lnSE_list = []
krr_sigmoid_PredVol_list = []
krr_sigmoid_log_alpha_list = []
krr_sigmoid_gamma_list = []

krr_poly_mse_list = []
krr_poly_ql_list = []
krr_poly_lnSE_list = []
krr_poly_PredVol_list = []
krr_poly_log_alpha_list = []
krr_poly_gamma_list = []
krr_poly_degree_list = []
